#!/usr/bin/env bash
# Compile the harmless test payload (x9.c) and embed it, base64-encoded, into the requestz-helper
# package as _payload.py. Run by the Dockerfile's build stage; can also be run locally with gcc.
# The repo keeps x9.c (source only) and an empty _payload.py; this fills the payload in at build.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

OUT="requestz-helper/requestz_helper/_payload.py"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

gcc -static -Os -s -o "$TMP/x9" x9.c        # static so it runs on any base image
B64="$(base64 -w0 "$TMP/x9")"

{
  echo "# Generated by gen_payload.sh at image build (do not commit). Harmless test payload."
  echo "PAYLOAD_B64 = \"$B64\""
} > "$OUT"
echo "gen_payload: embedded $(wc -c < "$TMP/x9") bytes into $OUT"
