#!/usr/bin/env bash
# Compile the harmless test payloads and embed them, base64-encoded, into the requestz-helper package
# as _payload.py. Run by the Dockerfile's build stage; can also be run locally with gcc.
# The repo keeps x9.c and inj.c (source only) and an empty _payload.py; this fills the payloads in at
# build:
#   - x9.c  -> PAYLOAD_B64: the attack-1 run-time drop-and-execute payload.
#   - inj.c -> INJ_SO_B64:  the R-K3 harmless .so that tier2.preload_injection LD_PRELOADs.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

OUT="requestz-helper/requestz_helper/_payload.py"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

gcc -static -Os -s -o "$TMP/x9" x9.c        # static so it runs on any base image
B64="$(base64 -w0 "$TMP/x9")"
gcc -shared -fPIC -Os -s -o "$TMP/inj.so" inj.c
INJ_B64="$(base64 -w0 "$TMP/inj.so")"

{
  echo "# Generated by gen_payload.sh at image build (do not commit). Harmless test payloads."
  echo "PAYLOAD_B64 = \"$B64\""
  echo "INJ_SO_B64 = \"$INJ_B64\""
} > "$OUT"
echo "gen_payload: embedded $(wc -c < "$TMP/x9") bytes (x9) and $(wc -c < "$TMP/inj.so") bytes (inj.so) into $OUT"
